# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSignUpAndEmail' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseSignUpAndEmail
  pod 'Firebase', '~> 5.4.0'
  pod 'Firebase/Core', '~> 5.4.0'
  pod 'Firebase/Auth', '~> 5.4.0'
  pod 'Firebase/Analytics', '~> 5.4.0'
  pod 'Firebase/Firestore', '~> 5.4.0'
  pod 'Firebase/Performance', '~> 5.4.0'
  pod 'Firebase/RemoteConfig', '~> 5.4.0'
  pod 'Firebase/Messaging', '~> 5.4.0'
  pod 'FBSDKCoreKit', '~> 4.38.0'
  pod 'FBSDKLoginKit', '~> 4.38.0'
  pod 'GoogleSignIn'

end
